name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Deploy
      - name: ''
        run: cd www/measdb.ru
      - name: 'Deploy' 
        run: git checkout -f main
