name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Deploy
      - name: 'Deploy'
        uses: appleboy/ssh-action@master
        with:
          host: 'vip41.hostiman.ru' 
          username: 's218953'
          key: ${{ secrets.KEY }}
          port: 8228
          script: 'ls www/measdb.ru'
