name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Deploy
      - name: 'Deploy'
        uses: appleboy/ssh-action@master
        with:
          host: 'ruvip42.hostiman.ru'
          port: 8228 
          username: 's218953'
          key: ${{ secrets.KEY }}          
          script: |
            cd www/measdb.ru
            git fetch origin main
            git reset --hard FETCH_HEAD 
